# Site settings
title: Conor B Murphy
tagline: The philosophy, science and engineering of peak performance
description: > # this means to ignore newlines until "baseurl:"
  The intersection of philosophy, neuroscience of flow states, and
  engineering peak performance
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://conorbmurphy.com" # the base hostname & protocol for your site

# Plugins
plugins:
  - jekyll-paginate

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"
